
platform :ios, '8.0'
# use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

target 'ZMWPhotoBrowserDemo' do
    
    pod 'DACircularProgress'
    pod 'MBProgressHUD'
    pod 'SDWebImage'
    
end

